### ISSUE TITLE
Class t3lib_lock not found in 7.4 when automatic configuration is enabled

### ISSUE THREAD

**Issue by tobiwollender** [helhum/realurl#6]
I'm using TYPO3 7.4 and this realurl version. When the automatic configuration is enabled (in extension settings), I get the following error:

<pre>Fatal error: Class 't3lib_lock' not found in /.../typo3/cms/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4349</pre>

If I deactivate it, the error is gone. Probably a problem with removed t3lib_lock class in TYPO3 7+?

**Comment by helhum** [comment]
Hm, there is not a single occurrence of t3lib_lock in the master branch. Which version are you using actually?

**Comment by helhum** [comment]
OK, this problem exists in 1.12.8, but not in 2.0.1 any more, which is the current version based on 1.12.8 but with a bunch of additional bugfixes

**Comment by helhum** [comment]
To be clear which tags I kind of support and which not, I deleted all unsupported (old) tags

**Comment by tobiwollender** [comment]
Ah, ok. I had 1.12.\* in my composer.json and unfortunately didn't check for any newer version.
