### ISSUE TITLE
Tagged "2.0.1" in git but backend says "2.0.0"

### ISSUE THREAD

**Issue by 7elix** [helhum/realurl#8]
Git tag states version number "2.0.1", but backend based on ext_emconf says "2.0.0".
Just minor confusion

**Comment by helhum** [comment]
Yeah, right. But I would not like to change the tag now. Will hopefully not forget to fix this when tagging 2.0.2

**Comment by helhum** [comment]
Tagging and versions still not smoothly intrgrated in my workflow. I'm currently in sync though :)
